# Generated by Django 3.2.7 on 2021-10-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_agw_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(blank='True', max_length=128, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key_created',
            field=models.DateTimeField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
    ]
